### ISSUE TITLE
Grial Sample project fails to build when upgraded to XF 4.5 with Grial 3.0.61-RC

### ISSUE THREAD

**Issue by IoTFier** [UXDivers/Grial-UI-Kit-Support#694]
### Description

Grial Sample project fails to build when upgraded to XF 4.5 with Grial 3.0.61-RC
Please see the screenshot of errors as shown

**Can you please provide XF 4.5 compatible code ?**
I am using Android X in my actual App code. So, this help will be appreciated.

### Steps to Reproduce

1. download a copy of Grial Sample full  project - with RTL - without Gorilla.
2. Upgrade XF to 4.5, Xamarin Essential to 1.5.1, Xamanimation to 1.3.0 and Grial to 3.0.61 RC. 
3. Build the solution and look for errors in the Error window.
3. Issues around FileImageSources were addressed as shown in the 2nd screenshot

### Expected Behavior

Code should compile with no errors.
I tried to address many errors on my own but there are some obvious ones that I think needs to be added in the code generated Grial Admin portal.

### Actual Behavior

Build fails.

### Basic Information

- Version with issue:
- Last known good version:
- IDE: VS 16.5
- Platform Target Frameworks: 
  - iOS: 13.3 
  - Android: 8.1 ,9 , 10
- Android Support Library Version:  
- Nuget Packages: All the packages that comes with the downloading of the code
- Affected Devices:

### Screenshots

![image](https://user-images.githubusercontent.com/26844611/76917313-06b08600-6891-11ea-8be2-72ccfc9abb75.png)

![image](https://user-images.githubusercontent.com/26844611/76917463-7d4d8380-6891-11ea-80af-d3897591a81e.png)

**Comment by jpbrocca** [comment]
Hi @IoTFier how have you been?
This is probably caused by 4.5 bindings issues. 

Please take a look at this xamarin forms issue:
https://github.com/xamarin/Xamarin.Forms/issues/9212

It was recently fixed in this version:
https://github.com/xamarin/Xamarin.Forms/releases/tag/release-4.5.0-sr1

Please try with that version and let me know how it goes. I also suggest not to update xamanimation to latest. 

Regards 
JP

**Comment by IoTFier** [comment]
Hi @jpbrocca , I am doing good thank you.

I am already using the XF artifact 4.5.0.396 from the XF sr1 link your provided above.

![image](https://user-images.githubusercontent.com/26844611/76987745-ad3c6b80-6911-11ea-976d-c0172be30ba9.png)

Which version of xamanimation should I rollback to ?

Thank you

**Comment by dirivero** [comment]
Please use xamanimation 1.2.0.

**Comment by IoTFier** [comment]
> Please use xamanimation 1.2.0.

Thank you Diego. It looks like I will have to wait for 4.5 SR2. 
With SR1 bindings are still failing.

**Comment by dirivero** [comment]
Yes, that's true. You can go back to latest 4.4 in the meantime.

**Comment by dirivero** [comment]
Hi @IoTFier,
The latest XF version 4.5.0.495 includes a fix for this. You can upgrade now.
Thanks!

**Comment by IoTFier** [comment]
Hi @dirivero, it is still not compiling for me .
It is erroring out for following error in MovieDetailPage.xaml on line # 18

<Thickness x:Key="Margins">20,0</Thickness>
